### ISSUE TITLE
Cannot connect to local SPIRE agent on macOS

### ISSUE THREAD

**Issue by rturner3** [spiffe/java-spiffe#16]
When executing java-spiffe on Mac against a local SPIRE server and SPIRE agent, I run into this error when trying to use the SpiffeIdManager:

```
Jul 29, 2019 5:15:38 PM spiffe.api.svid.X509SVIDFetcher$1 onError
SEVERE: Could not get SVID 
UNKNOWN
```

I was able to resolve this by changing `KQueueServerDomainSocketChannel ` to `KQueueDomainSocketChannel` here when setting up the Netty ManagedChannel:
https://github.com/spiffe/java-spiffe/blob/master/src/main/java/spiffe/api/svid/SpiffeEndpointChannelBuilder.java#L113

Example code to reproduce this error:

```
System.getProperties().put("spiffe.endpoint.socket", "/tmp/agent.sock");
SpiffeIdManager spiffeIdManager = SpiffeIdManager.getInstance();
System.out.println(spiffeIdManager.getCertificate());
```

**Comment by maxlambrecht** [comment]
Hi @rturner3! good catch! If you could submit a PR with that fix it would be awesome
Thanks!
