### ISSUE TITLE
New release with latest gRPC and Netty dependencies

### ISSUE THREAD

**Issue by bob-barrett** [spiffe/java-spiffe#256]
Is there a new release planned soon? Dependencies on gRPC and Netty have been updated on main since 0.8.6, but no new release has been cut. Given gRPC's [release policy](https://grpc.io/docs/what-is-grpc/faq/#how-long-are-grpc-releases-supported-for), 1.62 has been out of support for a while.

I'd be happy to help with preparing a release, if that would be useful, though I imagine most of it would need to be done by maintainers.

**Comment by moe-omar** [comment]
Closing this as v0.8.7 has been released https://github.com/spiffe/java-spiffe/releases/tag/v0.8.7 (thank you @maxlambrecht!)
